apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: go-portfolio-app
    namespace: argocd
spec:
    project: default
    source:
        repoURL: 'https://github.com/aqeeladil/go-portfolio-app'
        targetRevision: HEAD
        path: helm/go-portfolio-app-chart
    destination:
        server: 'https://kubernetes.default.svc'
        namespace: default
    syncPolicy:
        automated:
            selfHeal: true
    helm:
        valueFiles: 
          - values.yaml
            